// <auto-generated />
namespace LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AssignmentSubmission_and_navprop_ids_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssignmentSubmission_and_navprop_ids_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201607010740235_AssignmentSubmission_and_navprop_ids_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
